### PR TITLE
biribussi's code in the current directory structure w conversions

### PR DESCRIPTION
**Pull request by kastyr1984**
Need testing on all

### CODE REVIEW

**Comment by kastyr1984** [comment]
accidental duplicate of #12, please continue that work here

**Review by ghost — APPROVED** [review]
Testing right now, working as intended. I'm questioning if the script is really useful tho, if a crash happens "auto battle" will not be on, regardless of what is set in the correspondant option. For this to work, app needs to be stable

**Comment by kastyr1984** [comment]
Can we insert an Auto press? What happens with these clicks if there's a crash to main screen?

**Comment by ghost** [comment]
If we add an auto click into the cycle it would enable and disable auto battle with every press. Could work, but i was trying to keep clicks to a minimum since i personally think in explorations more clicks = more crashes. If a crash occurs i don't think it would change anything, even with the auto click, but that will affect movement, i'll test it a little right now

**Comment by ghost** [comment]
Maybe i got it with diagonal inputs, should restart on crash and not press the "support" or square enix page on title screen, while continually move the pg and pressing auto battle. Can you give it a go Kas? Unfortunately i must be off for a while, tested in memu 1280x720 and it's working right now. I still don't know how to modify files without creating a new pull request, so i'll leave you a pastebin with the new script here https://pastebin.com/EjNkJvG5

**Comment by kastyr1984** [comment]
Generated new commits in this branch with your latest code. I cannot test right now because I'm at work but I'll go ahead and merge if you say it's working.

**Pull request merged**
