### PR TITLE
Potential fixes for Vortex issue

### PR DESCRIPTION
**Pull request by kastyr1984**
Potential fix for issue #1

### CODE REVIEW

**Comment by ghost** [comment]
I'll download and test it right away, i'll leave it run all night and report back on how it works

**Comment by kastyr1984** [comment]
Thanks, @biribussi! As I mentioned this is pretty much directly from Mcgillby's suggestions and completely untested by me. It should either work fine or crash and burn pretty much immediately.

**Comment by ghost** [comment]
there's something wrong. The script does not press "next" on the missions screen, it clicks above the button,  here's a [screenshoot](http://imgur.com/a/alEvj) . I suppose it just needs to be a little further down the screen. I would fix it myself, but i'm completely ignorant on macro scripting

**Comment by kastyr1984** [comment]
Thanks. Looks like Mcgillby's off the cuff calculations were a bit off. I'll shoot for an adjustment of ~5 pixels and try again.

**Comment by ghost** [comment]
Still too high, "next" button is not being pressed. I've download the memu file from the "another attempt"commit, is that right? Sorry i've never used github

**Comment by kastyr1984** [comment]
Oh yeah, you've got it. How do I turn on the highlighting for the key presses in MEmu? I think that would really help me figure out placement for this.

**Comment by ghost** [comment]
Go to settings (not the memu ones, the android ones), scroll down and click on "about tablet/phone", then scroll all the way down, and click a bunch of times on the "build number" row. you'll have a notification that noe you have unlocked developers option. Go back one page and you should see "developer options", click it and enable "Show touches", and you're done

**Comment by ghost** [comment]
Uff.. guys, sorry if this is off topic, but mcgillby is out of control. He pm'ed me right now 

> Someone needs to take this down, have you seen all the people commenting about lost lapis? Do you not see how big of an issue this is? I have been working on perfecting my touchpoints since november and I have a 100% saftey record, go to any of my threads and point out one account of someone losing lapis. This is a slap in the face to me and all the work ive put in to ensureing end-user safety, ive made an offer to collaberate and hes ignoring me, he also is denying there is a fault in his scripts, i couldnt concentrate at work today because of it. I refuse to work with anyone that does not put end-user safety as top-priority, by leaving it up there in its flawed state shows me he does not yive a shit about the user at all.


And now is procediing to shit over the thread we are keeping up and redirecting everyone to his own, because "safety". This is really getting on my nerves

**Comment by kastyr1984** [comment]
I made another attempt at the fix. For some reason I'd ended up with the wrong version of the script as my basis for work.

**Comment by ghost** [comment]
This one seems to work just fine, it is build to refill lapis? i'll leave it go all night anyway

**Comment by kastyr1984** [comment]
It's the auto lapis script. I can apply the same fix to the other scripts, too, but I think this was the main one we were worried about because it would apparently go into the Vortex on a crash outside of battle and eat up lapis. With the changes made it should only end up with you staring at Fina's psyche or something like that.

**Comment by ghost** [comment]
It's np, i have just the 100 lapis on memu, this way we'll see if it refills nicely and what happens when it crashes

**Comment by Mcgillby** [comment]
after watching your new version with the fixes, your process is identical to mine. You guys are using "Show Touches" in developer options to see where the touch points are hitting? okay, you will notice a Y shape. The only difference between my version and your version is the clicks going right. They are completely unnessecary and do not cover any button or anything else needed to run shrine. if you use my suggested co-ordinates of 259:780 it will cover

  1. friend request deny
  2. connection error
  3. Bad friend error

and then the 2 clicks going right can be removed, further reducing the chance of entering unwanted dungeons if the situation arises. It should look like a hockey stick pointing left. The Y shape is not ideal. Either way im testing it now and its working in its current state. ill do more testing to ensure safety from lapis loss.

**Comment by Mcgillby** [comment]
>there's something wrong. The script does not press "next" on the missions screen, it clicks above the button, here's a screenshoot . I suppose it just needs to be a little further down the screen. I would fix it myself, but i'm completely ignorant on macro scripting

>Thanks. Looks like Mcgillby's off the cuff calculations were a bit off. I'll shoot for an adjustment of ~5 pixels and try again.

that looks like the bottom button press, not my co-ordinates.. not sure how that happened?

**Comment by Mcgillby** [comment]
Im not sure what the proposed change is for the vortex fix.. what are the co-ordinates, I think one of the two clicks going right should be removed, they are in the same area, and couldnt possibly both be needed for proper operation, I suggest we isolate the furthest right of the two and remove all inputs for it, but that will require also adjusting the timing. Does anyone have any suggestions?

**Comment by Mcgillby** [comment]
One way to get around the timing issue would be to change all the inputs to the same coordinates as the press for unit 1 or 3, that would also speed it up a few ms in latency between button presses at the bottom of the screen

**Comment by kastyr1984** [comment]
Hey, @biribussi, if this is working for you could you go ahead and tag it as a good review so I can do a merge into the main codebase?

**Comment by ghost** [comment]
I'll give it one more go right now and be right back, give me 5 minutes

**Comment by ghost** [comment]
Seems all right to me. Never hits auto, refill lapis, i could do some more testing leaving it overnight but i think it's safe. There is one thing i don't understand: at the very end of the script, the last two clicks are in the upper corners of the screen, left upper corner then right upper corner. Is that on purpose?

**Review by ghost — APPROVED** [review]

**Comment by kastyr1984** [comment]
I just made one more change that I believe removes those two clicks. Could you check over it?

**Comment by ghost** [comment]
on it

**Comment by ghost** [comment]
Aye, they're gone. I've checked friend requests also (when you bring a non friend unit and your friend list is not full) and they're correctly denied at the end of the run. Seems safe to me

**Comment by kastyr1984** [comment]
Awesome! I think Mcgillby's issue was coming from him using the non-standard MEmu setup. Could you approve the review and I'll merge into the master branch?

**Comment by ghost** [comment]
i think i already approved it

**Pull request merged**
