### PR TITLE
Attempt at fixing Mcgillby issue

### PR DESCRIPTION
**Pull request by kastyr1984**
This is related to ticket #6

### CODE REVIEW

**Comment by ghost** [comment]
I'll download Nox and test this asap

**Comment by ghost** [comment]
Something's wrong. The macro seems inverted on the Y axes, all the clicks happens in the upper part on the screen

edit: [screenshoot](http://imgur.com/a/g8rwQ) to clarify further. running on Nox V3.8 , 1280x720

**Comment by kastyr1984** [comment]
I just attempted the same general thing but swapped out the x-axis flip for a y-axis flip.

**Comment by ghost** [comment]
on it

**Comment by ghost** [comment]
Seems fine now. Nox run like shit on my computer and crashes almost costantly, but the placement is right now

**Review by ghost — APPROVED** [review]

**Comment by Mcgillby** [comment]
Nice, now thats sick man. So fast now.

**Comment by Mcgillby** [comment]
Working perfect.

**Comment by Mcgillby** [comment]
Are all the NOX files updated?

**Comment by kastyr1984** [comment]
They're all converted by the tool but each needs to be tested to determine if a y-axis flip is needed since only the one has it applied right now.

**Comment by Mcgillby** [comment]
just checked no refill, its mirrored on the Y-axis, i'm assuming thats what you mean

**Comment by Mcgillby** [comment]
same with LB FARMING, and NR+Timer, I think all but TMRefill720 need to be flipped.

**Comment by Mcgillby** [comment]
they are all the same, Mirrored on the Y-Axis, whatever fix you did for TMRefill should work for the others im assuming

**Comment by kastyr1984** [comment]
Please see pull request #11

**Pull request merged**
