### PR TITLE
Potential fixes for y-flipped Mcgillby macros.

### PR DESCRIPTION
**Pull request by kastyr1984**

### CODE REVIEW

**Comment by Mcgillby** [comment]
how do i accept contributer invite?

**Comment by Mcgillby** [comment]
https://github.com/kastyr1984/FFBE-Macros/blob/f77be6652a4fa0e218b40063217a484b6deb418f/Mcgillby/MEmu/y-flipped/no_refills_720-flipped.txt

The MEmu script is showing HIRO syntax, I think something went wrong.

**Comment by Mcgillby** [comment]
http://i.imgur.com/2SJFKY0.png

I found out something interesting, Any device displaying under 720x1280 will make these black bars appear. Tested with 480x854 and 540x960.

**Comment by Mcgillby** [comment]
Wrote a script for resolutions with black bars (480x854) its fast and uses little to no RAM and CPU, maybe you can try converting it to 540x960? This could potentailly fix crashing issues.

**Comment by Mcgillby** [comment]
34 seconds fast, 2 sec per run faster then 800x1280

**Comment by Mcgillby** [comment]
https://pastebin.com/9cK26Nq0

**Comment by ghost** [comment]
Tested both scripts for a couple of minutes Kas, the clicks placement is correct

**Comment by kastyr1984** [comment]
Out for a bit but conversion on these I already figured out a while ago.
You calculate the viewable y axis and then convert your coordinate to that
height and then add the distance between top of "physical screen" and start
of game screen. I think this may be an effect of portrait rather than
landscape resolution on some devices, or that may have just been an
incorrect theory of mine.

**Pull request merged**
