### PR TITLE
Need testing on autobattle script

### PR DESCRIPTION
**Pull request by ghost**
I've created a very basic script for users that would want to enter an exploration (for metal eggs farming). The scripts is simply 3 clicks. One for moving up, one for moving down, and one in the niddle (so if ther app crash it can be reopened). This script assumes that the user begins the mission, start first battle, press auto one time and then let the macro run. When all the battes in zone one are over, the user move the pg in zone and let the macro go again "allow tap to move" and "continuosly auto battle" must also be enabled. Tedted on memu 2.8.6 1280x700 and seems to work.  Can you guys test it a little and see if everything is order?

### CODE REVIEW

**Comment by kastyr1984** [comment]
Does continuous auto battle carry over between battles?

**Comment by ghost** [comment]
Yes, but in the first battle you still need to press AUTO one time

**Comment by Kawoxux** [comment]
I'm going to create a similar one tomorrow which starts from the begin screen (the one where it displays your party and your helper.)

Re auto battle. If you change it to the third option (right most) it will carry on auto throughout with needing to click auto in first fight.
Downside is If you forget and then go into another mission it will keep autoing until you switch it off

Sent from my Sony Xperia™ smartphone

---- biribussi wrote ----


Yes, but in the first battle you still need to press AUTO one time

**Comment by kastyr1984** [comment]
If we like what biribussi has done here and just want to add onto it, we can use my macro tool to merge macros and tack on something that will bring it in from the begin screen. I'm about to run some tests with his macro right now, I've just been experimenting with hand-writing macros to try to recreate button press issues.

**Comment by kastyr1984** [comment]
Accidentally closed and merged. Please continue work in #14

**Pull request merged**
